// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWgiZSFyxp9_6WV0NcnXx7BHBrUoIlvKE',
    appId: '1:45707841865:web:2308d1320cea9dc3b08a98',
    messagingSenderId: '45707841865',
    projectId: 'fir-bookmark-57b6c',
    authDomain: 'fir-bookmark-57b6c.firebaseapp.com',
    storageBucket: 'fir-bookmark-57b6c.appspot.com',
    measurementId: 'G-96G0PCFN7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMHT-JQSfLNJPFrtZwv-Cp42pB_U4yG2M',
    appId: '1:45707841865:android:a9f0d10aafdfde3bb08a98',
    messagingSenderId: '45707841865',
    projectId: 'fir-bookmark-57b6c',
    storageBucket: 'fir-bookmark-57b6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTeQSGS1AdqQqekuj6vBeNGMIWOtGX240',
    appId: '1:45707841865:ios:09443d1fef6c1039b08a98',
    messagingSenderId: '45707841865',
    projectId: 'fir-bookmark-57b6c',
    storageBucket: 'fir-bookmark-57b6c.appspot.com',
    iosBundleId: 'com.example.instagramApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTeQSGS1AdqQqekuj6vBeNGMIWOtGX240',
    appId: '1:45707841865:ios:d80638bd75f5dc01b08a98',
    messagingSenderId: '45707841865',
    projectId: 'fir-bookmark-57b6c',
    storageBucket: 'fir-bookmark-57b6c.appspot.com',
    iosBundleId: 'com.example.instagramApp.RunnerTests',
  );
}
